In [66]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [67]:
f = lambda x: x**3 - 10*x**2 + 5
f_prime = lambda x: 3*x**2 - 20*x
ref = 0.7346035077893032

In [68]:
def incremental(f,x0,b,h):
    x1 = x0 + h
    n = 1
    while f(x0) > 0 and f(x1) > 0:
        if x1 > b:
            return "None"
        x0 = x1
        x1 = x0 + h
        n+=1
    return x1, n

In [69]:
rows = []
tolerances = []

for i in range(1, 6):
    tol = 10**(-i)
    root, steps = incremental(f, 0, 1, tol)
    error = abs(ref - root)/ref*100
    tolerances.append(tol)
    rows.append([root, steps, error])

columns = ['Root', 'Steps', 'Error %']
pd.DataFrame(rows, index=tolerances, columns=columns)

            Root  Steps   Error %
0.10000  0.80000      8  8.902284
0.01000  0.74000     74  0.734613
0.00100  0.73500    735  0.053974
0.00010  0.73470   7347  0.013135
0.00001  0.73461  73461  0.000884

In [70]:
def bisection(f,x0,x1,tol):
    n = 1
    while abs(x0 - x1) > tol:
        x2 = (x0 + x1)/2
        if f(x0)*f(x2) < 0:
            x1 = x2
        if f(x1)*f(x2) < 0:
            x0 = x2
        n+=1
    return x1,n

In [71]:
rows = []
tolerances = []

for i in range(1, 6):
    tol = 10**(-i)
    root, steps = bisection(f, 0, 1, tol)
    error = abs(ref - root)/ref*100
    tolerances.append(tol)
    rows.append([root, steps, error])

columns = ['Root', 'Steps', 'Error %']
pd.DataFrame(rows, index=tolerances, columns=columns)

             Root  Steps   Error %
0.10000  0.750000      5  2.095891
0.01000  0.742188      8  1.032393
0.00100  0.735352     11  0.101831
0.00010  0.734619     15  0.002128
0.00001  0.734604     18  0.000051

In [72]:
def newton_raphson(f, f_prime, x0, tol=1e-6):
    x1 = x0 - f(x0)/f_prime(x0)
    n = 1
    while abs(x1 - x0) > tol:
        x0 = x1
        x1 = x0 - f(x0)/f_prime(x0)
        n += 1
    return x1, n

In [73]:
rows = []
tolerances = []

for i in range(1, 6):
    tol = 10**(-i)
    root, steps = newton_raphson(f, f_prime, 1, tol)
    error = abs(ref - root)/ref*100
    tolerances.append(tol)
    rows.append([root, steps, error])

columns = ['Root', 'Steps', 'Error %']
pd.DataFrame(rows, index=tolerances, columns=columns)

             Root  Steps       Error %
0.10000  0.735121      2  7.047776e-02
0.01000  0.734604      3  2.174372e-05
0.00100  0.734604      3  2.174372e-05
0.00010  0.734604      4  2.085625e-12
0.00001  0.734604      4  2.085625e-12

In [74]:
def secant(f, x0, x1, tol):
    n = 1
    while abs(x1 - x0) > tol:
        x2 = x1 - f(x1)*((f(x1) - f(x0))/(x1 - x0))**(-1)
        x0 = x1
        x1 = x2
        n += 1
    return x1, n

In [75]:
rows = []
tolerances = []

for i in range(1, 6):
    tol = 10**(-i)
    root, steps = secant(f, 0, 1, tol)
    error = abs(ref - root)/ref*100
    tolerances.append(tol)
    rows.append([root, steps, error])

columns = ['Root', 'Steps', 'Error %']
pd.DataFrame(rows, index=tolerances, columns=columns)

             Root  Steps       Error %
0.10000  0.737957      4  4.565530e-01
0.01000  0.734549      5  7.411134e-03
0.00100  0.734603      6  1.478748e-05
0.00010  0.734603      6  1.478748e-05
0.00001  0.734604      7  4.801321e-10

In [78]:
def ridders(f, x0, x1, tol):
    n = 1
    while abs(x0 - x1) > tol:
        x2 = (x0 + x1)/2
        x3 = x2 + (x1 - x0)*((f(x2)/f(x0))/(np.sqrt((f(x2)/f(x0))**2 - (f(x1)/f(x0)))))
        x0 = x2
        x1 = x3
        n += 1
    return x1, n

In [79]:
rows = []
tolerances = []

for i in range(1, 6):
    tol = 10**(-i)
    root, steps = ridders(f, 0, 1, tol)
    error = abs(ref - root)/ref*100
    tolerances.append(tol)
    rows.append([root, steps, error])

columns = ['Root', 'Steps', 'Error %']
pd.DataFrame(rows, index=tolerances, columns=columns)

             Root  Steps   Error %
0.10000  0.715505      3  2.599884
0.01000  0.734903      4  0.040739
0.00100  0.734903      4  0.040739
0.00010  0.734603      5  0.000004
0.00001  0.734603      5  0.000004